tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# utils 
brew "ansible"
brew "awk"
brew "awscli"
brew "cowsay"
brew "fzf"
brew "git"
brew "htop"
brew "nvm"
brew "ripgrep"
brew "stow"
brew "telnet"
brew "thefuck"
brew "tmux"
brew "zsh"

# casks
cask "discord"
cask "slack"
cask "1password"
cask "iterm2"
cask "google-chrome"
cask "google-drive"
cask "visual-studio-code"
cask "docker"
cask "ghidra"
cask "rectangle"
cask "raycast"
cask "obs"
cask "notion"
cask "spotify"
cask "suspicious-package"
cask "vlc"
cask "qlplugins which are nice"
cask "apparency "
cask "quicklookase "
cask "qlvideo"
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"
cask "qlimagesize"
cask "suspicious-package"
