tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "ansible"
brew "awk"
brew "awscli"
brew "cowsay"
brew "fzf"
brew "git"
brew "handbrake"
brew "htop"
brew "less"
brew "mas"
brew "neovim", args: ["HEAD"]
brew "nvm"
brew "openjdk"
brew "railway"
brew "ripgrep"
brew "rustup-init"
brew "stow"
brew "telnet"
brew "thefuck"
brew "tmux"
brew "zsh"
cask "1password"
cask "1password-cli"
cask "apparency"
cask "discord"
cask "docker"
cask "figma"
cask "ghidra"
cask "gimp"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "karabiner-elements"
cask "notion"
cask "obs"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "raycast"
cask "rectangle"
cask "slack"
cask "spotify"
cask "suspicious-package"
cask "visual-studio-code"
cask "vlc"
mas "HP Smart", id: 1474276998
mas "Microsoft Remote Desktop", id: 1295203466
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
