gui:
  theme:
    inactiveBorderColor:
      - '#707070'
    activeBorderColor:
      - "#ffffff"
    selectedLineBgColor:
      - 'black'
  authorColors:
      'Sean Boult': 'red'
  showBottomLine: false
  showCommandLog: false
git:
  overrideGpg: true
os:
  editPreset: "nvim" # see 'Configuring File Editing' section
keybinding:
  universal:
    quit: <c-c>
customCommands:
  - key: q
    context: global
    command: tmux select-window -t :1
    description: Return to editor
