- hosts: localhost
  tasks:
    - include_vars: packages.yaml
    - name: Install CLI Utils
      community.general.homebrew:
        name: "{{ item }}"
        state: present 
        path: "{{ lookup('ansible.builtin.env', 'HOMEBREW_PREFIX', default=Undefined) }}/bin"
      loop: "{{ cli_packages }}"
    - name: Install Desktop Apps
      community.general.homebrew:
        name: "{{ item }}"
        state: present 
        path: "{{ lookup('ansible.builtin.env', 'HOMEBREW_PREFIX', default=Undefined) }}/bin"
      loop: "{{ desktop_packages }}"