[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xf97583"
index = 17

[colors.bright]
black = "0x767676"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.normal]
black = "0x21252b"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.primary]
background = "0x21252b"
foreground = "0xabb2bf"

[env]
TERM = "alacritty"

[font]
size = 20

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
dynamic_padding = true

[window.padding]
x = 8
y = 2
