name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
env:
  NODE_VERSION: "18"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install libfuse
        run: sudo apt install libfuse2 -y
      - name: Link nvim config
        run: ln -s .config/nvim ~/.config/nvim
      - name: Install neovim@HEAD
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
          chmod u+x nvim.appimage
      - name: Run neovim
        run: CI_TEST=1 ./nvim.appimage
