name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
env:
  NODE_VERSION: "18"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      # write a shell check action to validate the scripts

