name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
env:
  NODE_VERSION: "18"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install native deps 
        run: sudo apt install curl git make cmake gcc fd-find ripgrep nodejs fzf -y
      - name: Link nvim config
        run: |
          whoami
          pwd
          ls -hal
          ln -s /home/runner/dotfiles/.config/nvim ~/.config/nvim
          ls -hal ~/.config/nvim
      - name: Install neovim@nightly
        run: |
          curl -sLO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
          tar xzvf nvim-linux64.tar.gz
      - name: Run neovim
        run: ./nvim-linux64/bin/nvim
