name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
env:
  NODE_VERSION: "18"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install libfuse
        run: sudo apt install libfuse2 -y
      - name: Link nvim config
        run: ln -s ./dotfiles/.config/nvim ~/.config/nvim
      - name: Install neovim@nightly
        run: |
          curl -sLO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
          tar xzvf nvim-linux64.tar.gz
      - name: Run neovim
        run: ./nvim-linux64/bin/nvim
        env: 
          CI_TEST: 1
