name: Devcontainer CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
    # build the devcontainer from .devcontainer.json
      - name: Build devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: mcr.microsoft.com/devcontainers/base
          imageTag: jammy
          runCmd: |
            echo all done 😊