name: Devcontainer CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
env:
  NODE_VERSION: "18"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
    # build the devcontainer from .devcontainer.json
      - name: Build devcontainer
        uses: devcontainers/ci@v0.3
