name: Devcontainer CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build and test devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            zsh -lc 'command -v brew fnm node pnpm rustup nvim starship'
          push: never
