name: Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  NODE_VERSION: "18"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install native deps 
        run: sudo apt install curl git make cmake gcc fd-find ripgrep nodejs fzf -y
      - name: Link nvim config
        run: ln -s /home/runner/work/dotfiles/dotfiles/.config/nvim ~/.config/nvim
      - name: Install neovim@nightly
        run: |
          curl -sLO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
          tar xzf nvim-linux64.tar.gz
      - name: Run neovim
        run: | 
          # remove the lock file so we get latest deps
          mv ~/.config/nvim/lazy-lock.json ~/.config/nvim/lazy-lock.original.json
          ./nvim-linux64/bin/nvim --headless -c 'exe !!v:errmsg."cquit"'

          # diff the original and the generated lazy-lock.json
          echo "lazy diff lazy-lock.original.json -> lazy-lock.json"
          diff -u --color ~/.config/nvim/lazy-lock.original.json ~/.config/nvim/lazy-lock.json && echo $? || true
