name: Nightly
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  NODE_VERSION: "18"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: ./.github/run-neovim.yaml
        with:
          channel: stable
