name: Neovim CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
env:
  NODE_VERSION: "18"
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint
        uses: lunarmodules/luacheck@v1.2.0
        with:
          args: .config
  stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install native deps 
        run: |
          sudo apt update
          sudo apt install curl git make cmake gcc fd-find ripgrep nodejs fzf -y
      - name: Link nvim config
        run: ln -s /home/runner/work/dotfiles/dotfiles/.config/nvim ~/.config/nvim
      - name: Install neovim@stable
        run: |
          curl -sLO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
          tar xzf nvim-linux-x86_64.tar.gz
      - name: Link neovim
        run: echo "$PWD/nvim-linux-x86_64/bin" >> $GITHUB_PATH
      - name: Validate neovim version
        run: nvim --version
      - name: Run neovim updated lockfile
        run: | 
          # remove the lock file so we get latest deps
          mv ~/.config/nvim/lazy-lock.json ~/.config/nvim/lazy-lock.original.json
          nvim --headless -c 'exe !!v:errmsg."cquit"'

          # diff the original and the generated lazy-lock.json
          echo "lazy diff lazy-lock.original.json -> lazy-lock.json"
          diff -u --color=always ~/.config/nvim/lazy-lock.original.json ~/.config/nvim/lazy-lock.json && echo $? || true
      - name: Run neovim original lockfile
        run: |
          # clear all neovim caches 
          rm -rf ~/.local/share/nvim
          rm -rf ~/.local/state/nvim
          rm -rf ~/.cache/nvim

          # remove the lock file from the run before
          rm ~/.config/nvim/lazy-lock.json 

          # run neovim with the original lockfile
          mv ~/.config/nvim/lazy-lock.original.json ~/.config/nvim/lazy-lock.json 
          nvim --headless -c 'exe !!v:errmsg."cquit"'
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install native deps 
        run: |
          sudo apt update
          sudo apt install curl git make cmake gcc fd-find ripgrep nodejs fzf -y
      - name: Link nvim config
        run: ln -s /home/runner/work/dotfiles/dotfiles/.config/nvim ~/.config/nvim
      - name: Install neovim@nightly
        run: |
          curl -sLO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz
          tar xzf nvim-linux-x86_64.tar.gz
      - name: Link neovim
        run: echo "$PWD/nvim-linux-x86_64/bin" >> $GITHUB_PATH
      - name: Validate neovim version
        run: nvim --version
      - name: Run neovim updated lockfile
        run: | 
          # remove the lock file so we get latest deps
          mv ~/.config/nvim/lazy-lock.json ~/.config/nvim/lazy-lock.original.json
          nvim --headless -c 'exe !!v:errmsg."cquit"'

          # diff the original and the generated lazy-lock.json
          echo "lazy diff lazy-lock.original.json -> lazy-lock.json"
          diff -u --color=always ~/.config/nvim/lazy-lock.original.json ~/.config/nvim/lazy-lock.json && echo $? || true
      - name: Run neovim original lockfile
        run: |
          # clear all neovim caches 
          rm -rf ~/.local/share/nvim
          rm -rf ~/.local/state/nvim
          rm -rf ~/.cache/nvim

          # remove the lock file from the run before
          rm ~/.config/nvim/lazy-lock.json 

          # run neovim with the original lockfile
          mv ~/.config/nvim/lazy-lock.original.json ~/.config/nvim/lazy-lock.json 
          nvim --headless -c 'exe !!v:errmsg."cquit"'

