name: Stable
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  NODE_VERSION: "18"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Neovim
        uses: ./.github/run-neovim
